services:
  - type: web
    name: ueba-backend
    env: python
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port 10000 --log-level info
